config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'posts#index'

  get '/about', to: 'pages#about'

  resources :charges
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <nav>
      <%= link_to "Blog", root_path %>
      <%= link_to "About", about_path %>

    </nav>

    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class:'alert') %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<h1>this is the about page blah blah blah</h1>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <%= pluralize(@post.errors.count, 'error') %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p><%=  f.label :title %>
  <%=  f.text_field :title %></p>

  <p><%=  f.label :body %>
  <%=  f.text_field :body %></p>

  <p><%=  f.submit %></p>
<% end %>

app/views/posts/edit.html.erb
<h1>new post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>posts home</h1>

<% @posts.each do |post| %>
  <div>
    <h2><%=link_to post.title, post %></h2>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>new post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <%= pluralize(@post.errors.count, 'error') %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p><%=  f.label :title %>
  <%=  f.text_field :title %></p>

  <p><%=  f.label :body %>
  <%=  f.text_field :body %></p>

  <p><%=  f.submit %></p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>


<% if user_signed_in? %>
  <%= link_to 'Edit', edit_post_path(@post) %>
  <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'are u sure?'} %>
<% end %>